[workspace]
resolver = "2"
members = [
    "apyee",
    "apyee-macros",
]

[workspace.package]
version = "0.6.0"
edition = "2021"
repository = "https://github.com/mztikk/apyee"
authors = ["Nils Feierabend <mztikk@outlook.de>"]
license = "MIT"
description = "yeelight api"