[package]
name = "apyee-macros"
description = "derive macro for get_params as JsValue"

repository.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full", "extra-traits"] }
